name: Deploy_To_Dev_Function_On_Push

on:
  push:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md' # don't run on README.md file updates anywhere in repo
      - '**/dependabot.yml'
      - '.github/workflows/prod-func-deploy.yml'
      - './pvt-post-solr-create-collections/exampleRequest.json'
    branches:
      - develop # update with develop when ready to deploy to Azure

env:
  STAGE: dev # suffix to indicate environment stage
  NAME: func-datastore-services
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x' # set this to the node version to use
  AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
  PGDATABASE: ${{ secrets.PGDATABASE_DEV }}
  PGHOST: ${{ secrets.PGHOST_DEV }}
  PGUSER: ${{ secrets.PGUSER_DEV }}
  PGPASSWORD: ${{ secrets.PGPASSWORD_DEV }}
  PGPORT: ${{ secrets.PGPORT }}
  PGSSL: ${{ secrets.PGSSL }}
  SOLR_URL: ${{ secrets.DEV_SOLR_API_URL }}
  SOLR_USERNAME: ${{ secrets.DEV_SOLR_USER }}
  SOLR_PASSWORD: ${{secrets.DEV_SOLR_PASSWORD }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.4.0

      - name: 'Setup Node ${{ env.NODE_VERSION }} Environment'
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          npm i -g npm
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm set-script prepare ""
          npm install --production
          popd

      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }} # Service Principal credentials saved in GitHub Secrets

      - name: Set Env variables for connecting to Redis instance and storing api keys in key vault
        uses: Azure/appservice-settings@v1.1.1
        with:
          app-name: ${{env.NAME}}-${{env.STAGE}}
          app-settings-json: |
            [
                {
                    "name": "PGDATABASE",
                    "value": "${{ env.PGDATABASE }}",
                    "slotSetting": false
                },
                {
                    "name": "PGHOST",
                    "value": "${{ env.PGHOST }}",
                    "slotSetting": false
                },
                {
                    "name": "PGUSER",
                    "value": "${{ env.PGUSER }}",
                    "slotSetting": false
                },
                {
                    "name": "PGPASSWORD",
                    "value": "${{ env.PGPASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "PGPORT",
                    "value": "${{ env.PGPORT }}",
                    "slotSetting": false
                },
                {
                    "name": "PGSSL",
                    "value": "${{ env.PGSSL }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_URL",
                    "value": "${{ env.SOLR_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_USERNAME",
                    "value": "${{ env.SOLR_USERNAME }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_PASSWORD",
                    "value": "${{ env.SOLR_PASSWORD }}",
                    "slotSetting": false
                }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.4.4
        with:
          app-name: ${{ env.NAME }}-${{ env.STAGE }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
