name: Deploy_To_PROD_Function_On_Release

# Runs when a Release is published from GitHub UI
on:
  release:
    types: [published]

env:
  STAGE: prod # suffix to indicate environment stage
  NAME: func-datastore-services
  AZURE_CREDENTIALS: ${{ secrets.PROD_AZURE_CREDENTIALS }}
  PGDATABASE: ${{ secrets.PGDATABASE_PROD }}
  PGHOST: ${{ secrets.PGHOST_PROD }}
  PGUSER: ${{ secrets.PGUSER_PROD }}
  PGPASSWORD: ${{ secrets.PGPASSWORD_PROD }}
  PGPORT: ${{ secrets.PGPORT }}
  PGSSL: ${{ secrets.PGSSL }}
  SOLR_URL: ${{ secrets.PROD_SOLR_API_URL }}
  SOLR_USERNAME: ${{ secrets.PROD_SOLR_USER }}
  SOLR_PASSWORD: ${{secrets.PROD_SOLR_PASSWORD }}
  STORAGE_CONNECTION_STRING: ${{ secrets.PROD_STORAGE_CONNECTION_STRING }}
  DOWNLOAD_CONTAINER_NAME: ${{ secrets.PROD_DOWNLOAD_CONTAINER_NAME }}
  KV_URI: ${{ secrets.PROD_KV_URI }}
  API_KEY: ${{ secrets.PROD_VALIDATOR_SERVICES_KEY_VALUE }}
  IATI_IDENTIFIERS_EXIST_MAX_NUMBER_OF_IDS: ${{ vars.PROD_IATI_IDENTIFIERS_EXIST_MAX_NUMBER_OF_IDS }}

jobs:
  build_save:
    uses: IATI/.github/.github/workflows/build_node_save.yaml@main
    with:
      npm_version: ^10
      save_artifact: true
      artifact_name: build-artifact-prod

  deploy:
    needs: build_save
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-prod

      - name: Unzip build artifact
        run: |
          unzip build-artifact-prod.zip
          rm build-artifact-prod.zip

      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.0
        with:
          creds: ${{ env.AZURE_CREDENTIALS }} # Service Principal credentials saved in GitHub Secrets

      - name: Set Env variables for connecting to Redis instance and storing api keys in key vault
        uses: Azure/appservice-settings@v1.1.1
        with:
          app-name: ${{env.NAME}}-${{env.STAGE}}
          app-settings-json: |
            [
                {
                    "name": "WEBSITE_NODE_DEFAULT_VERSION",
                    "value": "~16",
                    "slotSetting": false
                },
                {
                    "name": "PGDATABASE",
                    "value": "${{ env.PGDATABASE }}",
                    "slotSetting": false
                },
                {
                    "name": "PGHOST",
                    "value": "${{ env.PGHOST }}",
                    "slotSetting": false
                },
                {
                    "name": "PGUSER",
                    "value": "${{ env.PGUSER }}",
                    "slotSetting": false
                },
                {
                    "name": "PGPASSWORD",
                    "value": "${{ env.PGPASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "PGPORT",
                    "value": "${{ env.PGPORT }}",
                    "slotSetting": false
                },
                {
                    "name": "PGSSL",
                    "value": "${{ env.PGSSL }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_URL",
                    "value": "${{ env.SOLR_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_USERNAME",
                    "value": "${{ env.SOLR_USERNAME }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_PASSWORD",
                    "value": "${{ env.SOLR_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "STORAGE_CONNECTION_STRING",
                    "value": "${{ env.STORAGE_CONNECTION_STRING }}",
                    "slotSetting": false
                },
                {
                    "name": "DOWNLOAD_CONTAINER_NAME",
                    "value": "${{ env.DOWNLOAD_CONTAINER_NAME }}",
                    "slotSetting": false
                },
                {
                    "name": "AzureWebJobsSecretStorageType",
                    "value": "keyvault",
                    "slotSetting": false
                },
                {
                    "name": "AzureWebJobsSecretStorageKeyVaultUri",
                    "value": "${{ env.KV_URI }}",
                    "slotSetting": false
                },
                {
                    "name": "IATI_IDENTIFIERS_EXIST_MAX_NUMBER_OF_IDS",
                    "value": "${{ env.IATI_IDENTIFIERS_EXIST_MAX_NUMBER_OF_IDS }}",
                    "slotSetting": false
                }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: ${{ env.NAME }}-${{ env.STAGE }}

  integration-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for 3 minutes'
        run: sleep 180

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Install newman'
        run: |
          sudo npm i -g newman

      - name: 'Run integration tests'
        run: |
          newman run integration-tests/datastore-services-integration-tests.postman_collection.json \
            -e integration-tests/envs/func-datastore-services-prod.postman_environment.json \
            --env-var keyValue=$API_KEY \
            --delay-request 50
